# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web developer
email: your-email@domain.com
description: i am description on config yaml
baseurl: "/abc" # the subpath of your site, e.g. /blog
url: "http://http://brutalcrozt.github.io" # the base hostname & protocol for your site
twitter_username: enter_rebel
github_username:  brutalcrozt
github: [metadata]
lsi: false
source: ./jekyllDir
incremental: false
highlighter: rouge
gist:
  noscript: false
destination: ./jekyllOutput
# Build settings
markdown: kramdown
