# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web developer
author: Adi Prasetyo
email: hidden@from.spammer
logo: /static/img/avatar.png
description: A person who admires software engineering and fall in love with web
baseurl:  # the subpath of your site, e.g. /blog
url: "http://brutalcrozt.github.io" # the base hostname & protocol for your site
twitter_username: enter_rebel
github_username:  brutalcrozt
github: [metadata]
lsi: false
source: ./
collections:
  experiences:
    defaults:
      - scope:
          path: "./_experiences/"
          type: experiences
        values:
            layout: experience
    output: true
    # permalink: /experiences/:title
  en:
    defaults:
      - scope:
          path: "./_en/"
          type: posts
    output: true
  id:
    defaults:
      - scope:
          path: "./_id/"
          type: posts
    output: true

incremental: false
enableTags: true
# tagarray: []
paginate: 5
per_page: 20
paginate_path: "page:num"
highlighter: rouge
gist:
  noscript: false
gems:
    - jekyll-sitemap
    - jekyll-coffeescript
    - jekyll-paginate
    - jekyll-paginate-category
    - jekyll-gist
    - rouge
    - jekyll-watch
# Build settings
markdown: kramdown
