# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web developer
email: hidden@from.spammer
description: Person who admire software engineering and fall in love with web
baseurl:  # the subpath of your site, e.g. /blog
url: "http://brutalcrozt.github.io" # the base hostname & protocol for your site
twitter_username: enter_rebel
github_username:  brutalcrozt
github: [metadata]
lsi: false
source: ./
collections:
  experiences:
    defaults:
      - scope:
          path: "./_experiences/"
          type: experiences
        values:
            layout: experience
    permalink: /experiences/:title

incremental: false
highlighter: rouge
gist:
  noscript: false
gems:
    - jekyll-sitemap
    - jekyll-coffeescript
# Build settings
markdown: kramdown
